# automation.heating_working_on
# alias      : Heating - Working On
# unique_id  : 1760351004302
# state      : on
# last_trig  : 2026-05-04T05:30:00.056034+00:00
# mode       : single
# label      : heating

actions:
- action: climate.set_temperature
  data:
    hvac_mode: heat_cool
    temperature: 20
  metadata: {}
  target:
    device_id: 9f2b20efb917dd436d983286c23118c0
- device_id: b1b0827d1652fadcbbd3851a803c7715
  domain: switch
  entity_id: f8aee990c032884a19ab1cbf35190f4c
  type: turn_on
alias: Heating - Working On
conditions:
- condition: state
  entity_id: input_boolean.heating
  state: 'on'
description: ''
id: '1760351004302'
mode: single
triggers:
- entity_id:
  - schedule.working
  from: 'off'
  to: 'on'
  trigger: state
