# automation.new_automation_10
# alias      : Utility Room Floor Heating 
# unique_id  : 1771861053460
# state      : on
# last_trig  : 2026-08-25T06:00:00.009002+00:00
# mode       : single
# label      : heating

actions:
- action: climate.set_temperature
  data:
    temperature: 18
  metadata: {}
  target:
    device_id: 7704d502b1af96c82c7b9f38329405e1
alias: 'Utility Room Floor Heating '
conditions: []
description: ''
id: '1771861053460'
mode: single
triggers:
- entity_id:
  - schedule.utility_room_floor_heating
  from:
  - 'off'
  - 'on'
  trigger: state
